config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: %i[index show] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: %i[create destroy]

  resources :posts, only: %i[index show create destroy] do
    resources :comments, only: [:create]
    resources :likes,    only: %i[create destroy]
  end
  
  resources :search, only: [:index]

  resources :notifications, only: [:index]
  resources :terms_of_services, only: [:index]
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  belongs_to :post,    optional: true
  belongs_to :comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true

  # belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  # belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(25)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/helpers/notifications_helper.rb
# frozen_string_literal: true

module NotificationsHelper
end

app/views/notifications/index.html.slim
- notifications = @notifications.where.not(visitor_id: current_user.id)
- if notifications.exists?
  - notifications.each do |notification|
    - visitor = notification.visitor
    - visited = notification.visited
    = link_to "#{notification.visitor.name}さんが",user_path(visitor)
    - case notification.action
    - when 'follow'
      p あなたをフォローしました
    - when 'like'
      = link_to 'あなたの投稿',post_path(visited)
      p にいいねしました
    - when 'comment'
      = link_to 'あなたの投稿',post_path(visited)
      p にコメントしました
    hr
    = paginate notifications
- else
  p 
    | 通知はありません