config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: %i[index show] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: %i[create destroy]

  resources :posts, only: %i[index show create destroy] do
    resources :comments, only: [:create]
    resources :likes,    only: %i[create destroy]
  end
  
  resources :search, only: [:index]

  resources :notifications, only: [:index]
  resources :terms_of_services, only: [:index]
end

app/views/shared/_comment.html.slim
.comment_container
  .comment_user
    = gravatar_for comment.user
  .comment_texts
    .comment_user_name
      = link_to comment.user.name, user_path(comment.user)
    br
    .comment_content
      = comment.content
hr

app/views/shared/_footer.html.slim
footer.footer.bg-light
  .container
    -if user_signed_in?
      .text-center.display-4
        = link_to icon('far','image'),posts_path
      .text-muted.text-center
        p ©️kashiwamochi
    -else
      .text-muted.text-center
        p.copyright ©️kashiwamochi
    

app/views/shared/_header.html.slim
header 
  nav.navbar.navbar-expand-lg.navbar-light.bg-light
      a.navbar-brand[href=root_path]
        | Read to Lead
      button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"]
        span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        ul.navbar-nav.mr-auto
          li.nav-item.active
            a.nav-link[href=posts_path]
              | 投稿一覧
          li.nav-item
            -unless current_user.nil?
              a.nav-link[href=user_path(current_user)]
                = icon('fas','user')
          - if user_signed_in?
            li.nav-item
              a.nav-link[href=notifications_path]
                = icon('fas','bell')
          .search-form
            li.nav-item
              = search_form_for @search, url: search_index_path do |f|
                = f.text_field :title_cont, placeholder: '投稿を検索'
                = f.submit ('検索')

app/views/shared/_show_posts.html.slim
a.post-item href=post_path(post.id) = image_tag post.picture.url, :size =>'300x300'

app/views/shared/_stats.html.slim
- @user = User.find(params[:id])
.row
  .col-4.display-4
    p 投稿#{@user.posts.count}件
  .col-4.display-4
    a href=followers_user_path(@user) フォロワー#{@user.followers.count}人
  .col-4.display-4
    a href=following_user_path(@user) フォロー中#{@user.followers.count}人

app/views/shared/_user_info.html.slim
- @user = User.find(params[:id])
.row
  .col-4.display-1
    = gravatar_for @user
  .col-4
    p.display-1 #{ @user.name }
    p #{ @user.profile }
  .col-4.display-3
    p.p-3 = link_to icon('fas','user-edit'),edit_user_registration_path