config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: %i[index show] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: %i[create destroy]

  resources :posts, only: %i[index show create destroy] do
    resources :comments, only: [:create]
    resources :likes,    only: %i[create destroy]
  end
  
  resources :search, only: [:index]

  resources :notifications, only: [:index]
  resources :terms_of_services, only: [:index]
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  mount_uploader :picture, PictureUploader
  belongs_to :user

  has_many :comment,       dependent: :destroy
  has_many :likes,         dependent: :destroy
  has_many :notifications, dependent: :destroy

  has_many :liked_users, through: 'likes', source: 'user'

  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :picture, presence: true
  validates :title,   length: { maximum: 20 }
  validate  :picture_size

  # いいねされたときに通知を送る
  def create_notification_like(current_user)
    # すでにいいねされているかのチェック。いいねを連打されても通知は最初の一回しか来ない
    temp = Notification.where(['visitor_id = ? and visited_id = ? and post_id = ? and action = ?', current_user.id, user_id, id, 'like'])

    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分で自分の投稿にいいねした場合は、通知済みとする
      notification.checked = true if notification.visitor_id == notification.visited_id
      notification.save if notification.valid?
    end
  end

  # コメントされたときに通知を送る
  def create_notification_comment(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment(current_user, comment_id, visited_id)
    # コメントの場合は複数回通知が来るようにする
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿にコメントした場合、通知済みとする
    # notification.checked = true if notification.visited_id == notification.visitor_id
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end

  private

  def picture_size
    errors.add(:picture, 'should be less than 100MB') if picture.size > 100.megabytes
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[show create destroy]

  def index
    @user = current_user
    @posts = Post.all
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comment.all
    @comment = Comment.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:success] = '投稿されました'
      redirect_to post_path(@post.id)
    else
      flash[:danger] = '投稿に失敗しました'
      redirect_to root_path
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = '投稿が削除されました'
    redirect_to user_path(current_user)
  end

  private

  def post_params
    params.fetch(:post, {}).permit(:picture, :title)
    # params.require(:post).permit(:picture)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/index.html.slim
- provide(:title,'投稿一覧')

-if user_signed_in?
  .text-center
    h2 投稿する
    = form_for @post do |f|
      =  f.file_field :picture,accept: 'jpeg,png'
      br
      =  f.label :title
      br
      =  f.text_field :title
      br
      =  f.submit
    hr
h2.text-center みんなの投稿
.post-box
  = render :partial => 'shared/show_posts', :collection => @posts, as: 'post'

javascript:
  | $('#micropost_picture').bind('change', function() {
    | var size_in_megabytes = this.files[0].size/1024/1024;
    | if (size_in_megabytes > 5) {
      | alert('Maximum file size is 5MB. Please choose a smaller file.');
    | }
  | });

app/views/posts/show.html.slim
.container
    .row
        .col-6
            .row
                .col-6
                    p #{@post.title}
                .col-2
                    p #{@post.likes.count}
                .col-2
                    -if current_user.good?(@post)
                        = button_to post_like_path(@post),method: :delete do
                            i.fas.fa-heart
                    -else
                        = button_to post_likes_path(@post) do
                            i.far.fa-heart
                .col-2
                    - if @post.user == current_user
                        = link_to icon('fas','trash-alt'),post_path(@post.id),method: :delete
                        
            = image_tag @post.picture.url
        .col-6
            h2.text-center コメント
            = render :partial => 'shared/comment', :collection => @comments, as: 'comment'
            br
            = form_for [@post,@comment] do |f|
                = f.text_field :content
                br
                = f.submit 'コメントする'